version: '2.1'
name: radixdlt-babylon-node-3-core-network
services:
  core0:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core0
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_1_PUBKEY}@core1,radix://${RADIXDLT_VALIDATOR_2_PUBKEY}@core2"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_0_PRIVKEY}
    networks:
      - three_nodes
    ports:
      - "3333:3333"   # Core API
      - "3334:3334"   # System API
      - "3335:3335"   # Prometheus API
      - "9011:9011"   # JMX Port for Java debugging
      - "50505:50505" # JDWP Port for Java debugging
      # Gossip port on 30000 can be called by other nodes inside docker, but isn't exposed outside docker
  core1:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core1
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_0_PUBKEY}@core0,radix://${RADIXDLT_VALIDATOR_2_PUBKEY}@core2"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_1_PRIVKEY}
    networks:
      - three_nodes
    ports:
      - "3343:3333"
      - "3344:3334"
      - "3345:3335"
      - "8081:8080"
      - "9012:9011"
      - "50506:50505"
  core2:
    extends:
      file: core.yml
      service: core
    environment:
      RADIXDLT_HOST_IP_ADDRESS: core2
      RADIXDLT_NETWORK_SEEDS_REMOTE: "radix://${RADIXDLT_VALIDATOR_0_PUBKEY}@core0,radix://${RADIXDLT_VALIDATOR_1_PUBKEY}@core1"
      RADIXDLT_NODE_KEY: ${RADIXDLT_VALIDATOR_2_PRIVKEY}
    networks:
      - three_nodes
    ports:
      - "3353:3333"
      - "3354:3334"
      - "3355:3335"
      - "8082:8080"
      - "9013:9011"
      - "50507:50505"
networks:
  three_nodes:
